### ISSUE TITLE
Deleting an app threw an error

### ISSUE THREAD

**Issue by mbryzek** [mbryzek/apidoc#311]
likely webapp permission check doesn't match API

**Comment by rlmartin** [comment]
I was trying to delete this version http://www.apidoc.me/gilt/invoice-detail/2.0.0 (the endpoints are all 1.0, so I realized I didn't need it).

**Comment by nemo83** [comment]
:+1: bump!

**Comment by mbryzek** [comment]
Fix at http://github.com/mbryzek/apidoc/pull/412
