### ISSUE TITLE
Import of enums not properly handled in generated clients

### ISSUE THREAD

**Issue by yuanl1** [mbryzek/apidoc#342]
If importing a enum like so:
```javascript
{
          "method" : "GET",
          "path": "/:store",
          "parameters": [
            {
              "name": "store",
              "type": "com.gilt.public.api.enums.store"
            }
          ],
          "responses": {
            "200": {"type": "sale"}
          }
        }
```
The resulting generated client tries to use the model at com.gilt.public.api.enums.Store when the actual location of the model is com.gilt.public.models.Store.

**Comment by mbryzek** [comment]
Thanks - PR to fix this at:

https://github.com/gilt/apidoc-generator/pull/28

(removes the .enums and .unions and just uses .models everywhere)

**Comment by mbryzek** [comment]
Closing the issue as should be fixed in production
