### ISSUE TITLE
Invalid code generated for 'unit' post responses

### ISSUE THREAD

**Issue by Seanstoppable** [mbryzek/apidoc#348]
I have a POST endpoint that returns a unit. This results in a block of code being generated like the following:

def post_trigger_and_password_reset_request(password_reset_requested_event)
                HttpClient::Preconditions.assert_class('password_reset_requested_event', password_reset_requested_event, ::Com::Gilt::Consumer::Email::V0::Models::PasswordResetRequestedEvent)
                r = @client.request("/trigger/password-reset-request").with_json(password_reset_requested_event.to_json).post
                ::Com::Gilt::Consumer::Email::V0::Models::Value.new(r)
              end

Where 'Value' is not a valid class in this context.

**Comment by mbryzek** [comment]
Fixed here: https://github.com/mbryzek/apidoc-generator/pull/31 - in process of deploying

**Comment by mbryzek** [comment]
in production now - would be great if you can confirm the fix for you (and reopen if not what you expected).

thanks!
