### ISSUE TITLE
Clients should offer way to shutdown background threads

### ISSUE THREAD

**Issue by fiadliel** [mbryzek/apidoc#352]
For the Scala Ning clients, the underlying asyncHttpClient value is not publicly available. This means that it is (AFAIK) impossible to cleanly shutdown the thread pool.

Using this client, one way of shutting down the service is
```scala
try {
  ...
} finally {
  sys.exit(0)
}
```

But this is not appealing.

A simple forwarder like this might be sufficient:
```scala
def close(): Unit = asyncHttpClient.close()
```

**Comment by fiadliel** [comment]
Ah, actually I could pass in a client to the Client constructor, and close that client after use. But it still seems like a useful method for common cases.

**Comment by mbryzek** [comment]
I prefer to leave as is - rather than providing support for this specific use case
