### ISSUE TITLE
Vagrant/Puppet or something similar for deploy

### ISSUE THREAD

**Issue by dspeele** [mbryzek/apidoc#359]
Hey Michael,

I tried to use your Dockerfile to deploy the apidoc application locally but run into some trouble. I see that you have a deploy script (/web/ionroller-tools/bin/release-and-deploy --release "apidoc-api apidoc-www") but that it isn't included in the repo (or available publicly yet). It would be nice to be able to deploy the app to test branches. Any thoughts on this? I'd be happy to put something together.

Regards,

Dana

**Comment by mbryzek** [comment]
Just made https://github.com/mbryzek/ionroller-tools public - 'ionroller' comes from a tool at gilt to manage deployments to EC2 that will be open source soon (but is not a requirement for creating the docker image). the --release option will thus not work (unless you are private inside gilt). Note that I'm currently deploying the docker images directly to ec2.

I've just updated the docs to remove mention of the --release flag (which we're not using anymore).

For testing, I've been running locally per the instructions in DEVELOPER.md - if you end up testing by first building the docker images - would love to know how that works out
