### ISSUE TITLE
Support for Swagger docs with arrays inside of parameter object

### ISSUE THREAD

**Issue by dspeele** [mbryzek/apidoc#361]
Valid Swagger documents fail when they contain parameters of type array, regardless of the underlying type of the array. Pull request opened with extremely simple swagger json and test which tries to parse it and fails.

**Comment by dspeele** [comment]
Awesome, complex swagger like the file I was trying to use are importing perfectly now! Thanks for working on this, Michael. You can close this and my other issues if you'd like.

Regards,

Dana

**Comment by mbryzek** [comment]
Thank you Dana! Sorry took awhile to release (just got back from vacation
this week)
