### ISSUE TITLE
Error when changing project's visibility to public

### ISSUE THREAD

**Issue by nataliab** [mbryzek/apidoc#367]
Please see attached screen
![screen shot 2015-09-14 at 14 36 07](https://cloud.githubusercontent.com/assets/1488329/9851137/102e57c0-5aef-11e5-8d75-97a568309456.png)

**Comment by mbryzek** [comment]
Thanks! will fix- how urgent?

**Comment by nataliab** [comment]
Would be great if this could be fixed this week. Thanks!

**Comment by mbryzek** [comment]
you got it! congrats on open sourcing - very exciting!
