### ISSUE TITLE
please delete generator with key java_models_via_mobile_lambda

### ISSUE THREAD

**Issue by mchimirev** [mbryzek/apidoc#372]

**Comment by mbryzek** [comment]
have released a new version of apidoc with the ability to delete generator services.

Goto:
  http://www.apidoc.me/generators/servies/d1395bb5-ee13-42e5-8eaa-7afae9d264ef/show

As the author, you should see a link to delete

Once deleted, re-add the generator and it will resync immediately the generators provided by that service

**Comment by mbryzek** [comment]
Confirmed that UI change allowed successful delete
