### ISSUE TITLE
Generated client for nested union types does not compile

### ISSUE THREAD

**Issue by zcohn** [mbryzek/apidoc#376]
play_2_x_json generated client for nested union types does not generate consistent paths/names of the jsonReads/Writes methods.

See below for a minimal example of api.json.

    {
      "name": "nested_union",
      "description": "play_2_x_json generated client for nested union types does not compile",
      "unions": {
        "inner_type": {
          "types": [
            {
              "type": "string_model"
            }
          ]
        },
        "outer_type": {
          "types": [
            {
              "type": "inner_type"
            }
          ]
        }
      },
      "models": {
        "string_model": {
          "fields": [
            {
              "name": "name",
              "type": "string"
            }
          ]
        }
      }
    }

**Comment by mbryzek** [comment]
thanks! will fix

**Comment by mbryzek** [comment]
Fix here: https://github.com/mbryzek/apidoc-generator/pull/52 - will be deployed shortly

**Comment by mbryzek** [comment]
in production now
