### ISSUE TITLE
Json generator: null values now placed in json

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#396]
I notice that in latest apidoc (0.11.4), the json generator has been updated. The json generated now contains null values where they used to be absent. 

Is this intentional? 

Thanks

**Comment by RoryH** [comment]
+1

**Comment by mbryzek** [comment]
Thanks for reporting - not intentional and we'll fix (looking into the bug now and if quick will have a patch shortly)

**Comment by mbryzek** [comment]
FYI - fixed in https://github.com/mbryzek/apidoc-generator/pull/64 and will be deployed today

**Comment by mbryzek** [comment]
fix is in production

**Comment by JennyLeahy** [comment]
Thanks!
