### ISSUE TITLE
Search exception

### ISSUE THREAD

**Issue by krschultz** [mbryzek/apidoc#397]
Seems like queries that should return results in the applications list cause exception.

Failures:
http://apidoc.me/search?q=org%3Agilt+test
http://apidoc.me/search?q=org%3Agilt+install

Returns no results successfully:
http://apidoc.me/search?q=org%3Agilt+test2

**Comment by mbryzek** [comment]
Thanks for reporting. This comes from an API change to use the new discriminator. We have cleared the search table and queued up the applications for re-indexing which means they should shortly be available.
