### ISSUE TITLE
New Json generator: mandatory decimal field returning as string 

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#398]
Example:
If a field is defined as:
{ "name": "price", "type": "decimal" }

The json generated is:
"price": "4320"

However, this is no issue for optional field. 
Example:
{"name": "cost", "type": "decimal", "description":"The shipping method localised cost", "required": false }

The json generated is:
"cost": 7.95

**Comment by mbryzek** [comment]
Thanks!

Fix is here - https://github.com/mbryzek/apidoc-generator/pull/67 - will be deployed shortly

**Comment by mbryzek** [comment]
Now in production
