### ISSUE TITLE
Json generator: decimal fields return as strings

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#399]
I raised an issue last week: https://github.com/mbryzek/apidoc/issues/398
I think there is some misunderstanding. The decimal fields should return as numbers not strings in generated json file. For example:
If a field is defined as: { "name": "price", "type": "decimal" }
The correct json should be: "price": 4320
The actual generated json is : "price": "4320"

Optional decimal field was ok but now it also returns string instead of numbers:
However, this is no issue for optional field. 
Example:
{"name": "cost", "type": "decimal", "description":"The shipping method localised cost", "required": false }
The actual json generated is:
"cost": "7.95"

**Comment by mbryzek** [comment]
Ah - just fixed that as well - will be released shortly

**Comment by JennyLeahy** [comment]
Hi Mike, wondering if this is deployed? Thanks a lot

**Comment by mbryzek** [comment]
yes sorry - deployed yesterday
