### ISSUE TITLE
DNS Name Lookup failure

### ISSUE THREAD

**Issue by kiambogo** [mbryzek/apidoc#402]
I'm experiencing a recurring DNS name lookup failure when visiting apidoc.me and any subpaths. The problem seems to come and go, usually resolving within a few minutes and dropping again sporadically. 
At the time of writing this I'm not able to resolve the host.

     curl -X GET apidoc.me
     curl: (6) Could not resolve host: apidoc.me

**Comment by kalmanb** [comment]
We had the same issue. Seems like the DNS lookups are throttled. It comes back after a few mins.

**Comment by kalmanb** [comment]
A work around is to use googles DNS servers.

**Comment by kiambogo** [comment]
Thanks @kalmanb! Switching to Google's DNS servers seems to work. :+1:

**Comment by kalmanb** [comment]
@mbryzek this one should probably be looked at though. It caught us out when starting to use apidoc.

**Comment by mbryzek** [comment]
thanks! interesting - will keep in mind and pls let me know if you see this again
