### ISSUE TITLE
Routes generator doesn't handle enums properly.

### ISSUE THREAD

**Issue by Seanstoppable** [mbryzek/apidoc#407]
Routes generator does not handle enums properly.

With the following enum:

```json
enums: {
    review_state: {
      description: Status of attribution type,
      values: [
        { name: ALL, description: All states, for use in filtering },
        { name: WHITELISTED, description: Attribution reason is generally good },
        { name: BLACKLISTED, description: Attribution type is no good },
        { name: REVIEW, description: Attribution reason has not been reviewed }
      ]   
    }   
  }
```

And the following endpoint:

```
     operations: [
          {   
            method: GET,
            path: /:domain/clients,
            description: Return any clients for the given domain,
            parameters: [
              { name: domain, type: string, description: Domain name to filter by. Exact match },
              { name: review_state, type: review_state, default: WHITELISTED }
            ],
            responses: {
              200: { type: [relationship] }
            }
          }
```

I get the following route:

GET     /relationships/:domain/clients     controllers.Relationships.getClientsByDomain(domain: String, review_state: com.securityscorecard.v1.svc.avd.v0.models.ReviewState ?= com.securityscorecard.v1.svc.avd.v0.models.ReviewState("com.securityscorecard.v1.svc.avd.v0.models.ReviewState("WHITELISTED")"))

Which doesn't compile.

Changing it to the following works

GET     /relationships/:domain/clients     controllers.Relationships.getClientsByDomain(domain: String, review_state: com.securityscorecard.v1.svc.avd.v0.models.ReviewState ?= com.securityscorecard.v1.svc.avd.v0.models.ReviewState.Whitelisted)

**Comment by mbryzek** [comment]
Fix at https://github.com/mbryzek/apidoc-generator/pull/74

**Comment by mbryzek** [comment]
deployed and fixed in production
