### ISSUE TITLE
Rails treats enum query parameters as objects

### ISSUE THREAD

**Issue by Seanstoppable** [mbryzek/apidoc#408]
Ended up with:

GET http://localhost:9000/relationships/gilt.com/vendors?review_state=%23%3CCom%3A%3ASecurityscorecard%3A%3AV1%3A%3ASvc%3A%3AAvd%3A%3AV0%3A%3AModels%3A%3AReviewState%3A0x007fcd50038ed0%3E' [Unrecognized review_state, should be one of ALL, WHITELISTED, BLACKLISTED, REVIEW]

Should instead make sure to use the 'value', which would give us:

GET http://localhost:9000/relationships/gilt.com/vendors?review_state=WHITELISTED

**Comment by mbryzek** [comment]
thanks sean - working on a fix

**Comment by Seanstoppable** [comment]
Thanks. I started a fix and then got hung up on testing.

- Sean

**Comment by mbryzek** [comment]
fix is at: https://github.com/mbryzek/apidoc-generator/pull/73

**Comment by mbryzek** [comment]
deployed and fixed in production

**Comment by Seanstoppable** [comment]
Thanks!
