### ISSUE TITLE
Map(s) don't support List or Seq of objects

### ISSUE THREAD

**Issue by nemo83** [mbryzek/apidoc#410]
Hi,

In my api I would like to return a map that associate a String to List[Long]. Unfortunately I don't seem to be able to achieve this without introducing a RichType that simply wraps the List[Long].

Is this done on purposes? In case it is not, are you planning to introduce this feature?

Thanks,
Gio

**Comment by mbryzek** [comment]
This is a supported use case - so likely a bug in one of the code generators. Would it be possible for you to post a sample api.json specification and a link to the code generator you are using?

**Comment by nemo83** [comment]
Hi,

so a simple example I came up with is with a model that comprehends Person and Colour.

I could design an endpoint for Colour that returns a map from Person to "Preferred" Colour.

`{
  "name": "my-simple-service",
  "base_url": "http://my-simple-service",
  "description": "Simple Example",
  "models": {
    "person": {
      "description": "A person",
      "fields": [
        {
          "name": "name",
          "type": "string"
        }
      ]
    },
    "colour": {
      "description": "A colour",
      "fields": [
        {
          "name": "name",
          "type": "string"
        }
      ]
    }
  },
  "resources": {
    "colour": {
      "path": "/colour",
      "operations": [
        {
          "method": "GET",
          "path": "/coloursByPerson",
          "responses": {
            "200": {
              "type": "map[colour]"
            }
          }
        }
      ]
    }
  }
}`

with the snippet above I can map a Person to a Colour, via the `map[colour]` syntax, but if I attempt to change it to `map[[colour]]` I get the following error at upload time:

> Resource[colour] GET /colour/coloursByPerson response code[200] has an invalid type[map[[colour]]].

Hope it helps

**Comment by mbryzek** [comment]
Thanks - helpful - have replicated and looking into solutions.

**Comment by mbryzek** [comment]
Will be fixed in production shortly
