### ISSUE TITLE
Play client doesn't respect custom Content-Type for POST/PUT

### ISSUE THREAD

**Issue by paololim** [mbryzek/apidoc#430]
For one of the integrations we are working on at Flow, the API requires us to pass a non-standard Content-Type as part of the request headers:
```
Content-Type: application/vnd.com.xxxxx.shipping.v1+json
```

But looks like when the client is generated, the POST and PUT requests are forced to have application/json, regardless of what `requestHeaders` were passed to `_executeRequest`:
```
_requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*).withHeaders("Content-Type" -> "application/json; charset=UTF-8")).post(body.getOrElse(play.api.libs.json.Json.obj())
```

**Comment by mbryzek** [comment]
see: https://github.com/mbryzek/apidoc-generator/pull/81

**Comment by mbryzek** [comment]
Patch released to production
