### ISSUE TITLE
Site chokes on attributes

### ISSUE THREAD

**Issue by pierods** [mbryzek/apidoc#432]
This json causes an error (red stripe with some error code) - error goes away if attributes are removed:

{
  "name": "Echo",
  "apidoc": {
    "version": "0.11.23"
  },
  "info": {},
  "base_url": "mazimi-prod.apigee.net/echo",
  "description": "ciao",
  "models": {
    "user": {
      "fields": [
        {
          "name": "guid",
          "type": "string",
          "description": "a global uid",
          "required": true,
          "example": "067e6162-3b6f-4ae2-a171-2470b63dff00",
          "attributes": [
            {
              "name": "format",
              "value": "uuid"
            }
          ]
        }
      ]
    }
  },
  "resources": {
    "user": {
      "operations": [
        {
          "method": "POST",
          "path": "/user",
          "parameters": [
            {
              "name": "name",
              "type": "string",
              "location": "form",
              "description": "name",
              "required": false
            },
            {
              "name": "year",
              "type": "string",
              "location": "form",
              "description": "year",
              "required": false
            }
          ],
          "responses": {
            "200": {
              "type": "user",
              "description": "Echo POST"
            }
          }
        },
        {
          "method": "GET",
          "path": "/user",
          "parameters": [],
          "responses": {
            "200": {
              "type": "user",
              "description": "Echo GET"
            }
          }
        }
      ]
    }
  }
}

**Comment by chrisbarrett** [comment]
An attribute value must be a JSON object literal.

**Comment by chrisbarrett** [comment]
```
api.json:21:24: error: Expected "object", but got "string".
              "value": "uuid"
                       ~~~~~~
```

**Comment by mbryzek** [comment]
Thanks so much for reporting this issue and providing the sample - very helpful. This identifies a core bug where we are NOT reporting validation errors for attributes internally. I've got this in my backlog to fix (and let me know if urgent).

One alternative suggestion for how to use the attribute - if you are pulling in some metadata from say a swagger model, you can name your attribute "swagger" and make the value a JSON object of all the additional swagger metadata:

          "attributes": [
            {
              "name": "swagger",
              "value": { "format": "uuid" }
            }
          ]

The benefit here is when you actually go to use the attribute in the code generator - you will have one place that takes a swagger attribute and you will have ALL of the metadata available.

**Comment by mbryzek** [comment]
FYI - validation errors are now properly reported in production. Change completed in PR https://github.com/mbryzek/apidoc/pull/433

**Comment by pierods** [comment]
Many thanks.
@chrisbarrett Well yes, the type would be uuid, but since I am actually translating from swagger, in which I have type = string and format = uuid, I want to record the info somewhere, so I tried to use an attribute. Eventually I'll translate straight into type = uuid

@mbryzek Thanks, I did exactly what you suggested.

**Comment by chrisbarrett** [comment]
Gotcha. Thanks, I was missing the context. 😇
