### ISSUE TITLE
Generated play client - play.api.libs.json.Reads.DefaultJodaDateReads 

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#458]
It seems the latest generator has replaced the implicit jsonReadsJodaDateTime() with play default (play.api.libs.json.Reads.DefaultJodaDateReads) for play 2.3 client.  It has caused parsing error. 

The generated client has following removed:

    private[v0] implicit val jsonReadsJodaDateTime = __.read[String].map { str =>
      import org.joda.time.format.ISODateTimeFormat.dateTimeParser
      dateTimeParser.parseDateTime(str)
    }

Instead, a new import is added:
import play.api.libs.json.Reads.DefaultJodaDateReads

**Comment by mbryzek** [comment]
odd - tests passed locally for us here in play 2.3. If you could share the full error - that would be much appreciated. 

In interim, have reverted teh change (deploying now)

**Comment by fiadliel** [comment]
Play on master has removed support for Joda Time, in favour of standard `java.time` types: https://github.com/playframework/playframework/pull/6340

It looks like (for released versions), DefaultJodaDateReads uses the format "yyyy-MM-dd", not ISO-8601 encoding. There is an `IsoDateReads` which does ISO-8601 reads, but it saves the result in a `java.util.Date`.

**Comment by JennyLeahy** [comment]
Gary was right. The error says:
JsError(List((/date_created,List(ValidationError(List(error.expected.jodadate.format),WrappedArray(yyyy-MM-dd))))))

**Comment by mbryzek** [comment]
thanks!

FYI: reverted in production now - sorry about the bug

**Comment by JennyLeahy** [comment]
Great! Thanks!
