### ISSUE TITLE
apidoc.me down?

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#468]
504 error returns when visiting www.apidoc.me. It has been happening since yesterday (9th Oct).

**Comment by mbryzek** [comment]
Thanks @JennyLeahy - we did see it flap a few times yesterday.

Restarted services and they are back, but note may see a bit more instability in short term until we move apidoc to its new home (w/ additional resources behind it) - hopefully will be moved by end of this week.

**Comment by JennyLeahy** [comment]
Thanks! :-)

**Comment by mbryzek** [comment]
FYI - we've upgraded the instance type of apidoc to solve the core issue (OOM) and also refactored to use dependency injection and to setup dedicated threadpools for the actors (Which caused contention in API). change is here if interested:

https://github.com/mbryzek/apidoc/pull/469

Production DB also upgraded to psql 9.5

Note we plan to move to another AWS account and add additional resources as well - but this *should* resolve instability from the weekend
