### ISSUE TITLE
Error regarding model with plural (related to issue 491)

### ISSUE THREAD

**Issue by JennyLeahy** [mbryzek/apidoc#567]
I think this is related to issue
https://github.com/mbryzek/apidoc/issues/491

Now when uploading my previous successful api.json without any changes, I get following error:
`Model with plural[countries] appears more than once`

In my api.json, there is only one model with name "countries":
`
    "countries": {
      "fields": [
        { "name": "available_countries", "type": "[country]" }
      ]
    }
`
However, I have a resource called the same name.

`
    "countries": {
      "path": "/countries",
      "operations": [
        {
          "method": "GET",
          "description": "Returns the list of countries for display on checkout",
          "responses": {
            "200": {"type": "countries"},
            "404": {"type": "unit"}
          }
        },
        {
          "method": "GET",
          "path": "/:country_code/states",
          "responses": {
            "200": {"type": "[state]"},
            "404": {"type": "unit"}
          }
        }
      ]
    }

`

**Comment by JennyLeahy** [comment]
I don't think updating the model name or the resource name is practical for us

**Comment by mbryzek** [comment]
any chance you can upload your json file here?

**Comment by JennyLeahy** [comment]
Here is content of the json file (I just tried and got the same error):

{
  "base_url": "https://www.gilt.com/api-checkout",
  "name": "Checkout Api",
  "description": "Checkout Api provides api for checkout applications, it provides authentication and converts order model to a display friendly checkout model",
  "apidoc": {
    "version": "0.9.6"
  },
  "enums": {
    "checkout_session_creation_strategy": {
      "description": "List of checkout session creation strategy.",
      "values": [
        {"name": "shared", "description": "creates a shared session that affects user's checkout session on all devices."}
      ]
    }
  },
  "models": {
    "status": {
      "description": "Response for ping and health check.",
      "fields": [
        { "name": "response", "type": "string" }
      ]
    },
    "address": {
      "description": "Represents a physical address - e.g. an address to where to ship goods or a billing address for a credit card. We have an open question right now on whether or not billing and destination addresses are actually the same.",
      "fields": [
        { "name": "guid", "type": "uuid", "required": false},
        { "name": "first_name", "type": "string", "required": false },
        { "name": "last_name", "type": "string", "required": false },
        { "name": "line1", "type": "string" },
        { "name": "line2", "type": "string", "required": false },
        { "name": "line3", "type": "string", "required": false },
        { "name": "city", "type": "string", "required": false },
        { "name": "state", "type": "string", "required": false },
        { "name": "postal_code", "type": "string", "required": false },
        { "name": "country", "type": "string" },
        { "name": "phone_number", "type": "string", "required": false },
        { "name": "is_default", "type": "boolean", "required": false }
      ]
    },
    "countries": {
      "fields": [
        { "name": "available_countries", "type": "[country]" }
      ]
    },
    "country": {
      "fields": [
        { "name": "iso3166Two", "type": "string" },
        { "name": "name", "type": "string" },
        { "name": "shippable", "type": "boolean" },
        { "name": "billable", "type": "boolean" },
        { "name": "requires_postal_code", "type": "boolean" },
        { "name": "default_currency_code", "type": "string", "required": false },
        { "name": "country_id", "type":"long", "description" :"Gilt's numeric ID for the Country "},
        { "name": "states", "type": "[state]", "description": "All states for this country."}
      ]
    },
    "state": {
      "fields": [
        { "name": "id", "type": "long" },
        { "name": "code", "type": "string" },
        { "name": "name", "type": "string" }
      ]
    }
  },
  "resources": {
    "countries": {
      "path": "/countries",
      "operations": [
        {
          "method": "GET",
          "description": "Returns the list of countries for display on checkout",
          "responses": {
            "200": {"type": "countries"},
            "404": {"type": "unit"}
          }
        },
        {
          "method": "GET",
          "path": "/:country_code/states",
          "responses": {
            "200": {"type": "[state]"},
            "404": {"type": "unit"}
          }
        }
      ]
    }
  }
}

**Comment by mbryzek** [comment]
the issue is that there are two models:

`countries`
and
`country`

both of these will have the same plural `countries` - and recently a bug was fixed that allowed this through. The problem w/ duplicate plurals is you cannot identify the model by plural.

The solution is to rename one of these models (or alternatively specify an alternative plural for say the `countries` models

**Comment by JennyLeahy** [comment]
```
"countries": {
      "fields": [
        { "name": "available_countries", "type": "[country]" }
      ]
    },
```
"countries" is an array of "country", this is always the way we define an array of objects. How you propose to change?

**Comment by gheine** [comment]
You can either rename the "countries" type to countries_list or available_countries, or change the plural for the "country" type to e.g. "countrys" or "multiple_countries" (sorry, can't come up with anything better than that)

**Comment by JennyLeahy** [comment]
@gheine breaking change it will be, all checkout clients have to be updated :-(

**Comment by JennyLeahy** [comment]
adding a specified "plural" solved the issue.
Thanks for the help. @mbryzek @gheine
