### ISSUE TITLE
Adding/removing discriminator key on union type considered a breaking change

### ISSUE THREAD

**Issue by kyle-dorman** [mbryzek/apidoc#575]
Is adding/removing/changing a discriminator key on a union type is considered a breaking change? I tested removing a discriminator key from a union and was not warned of a breaking change.

**Comment by mbryzek** [comment]
you're right - we should track removing discriminator as breaking

**Comment by mbryzek** [comment]
what did you mean by:

```
I just didn't see it come up on the main page when I uploaded a new version.
```

**Comment by kyle-dorman** [comment]
I thought that when you upload a new version with breaking changes you get a message on the main api page that warns you about the breaking changes. But I just tested with a different breaking change and I didn't see any breaking change message, so maybe I am misremembering things.

**Comment by mbryzek** [comment]
ah -understood. At the moment, apidoc does NOT block any changes, just reports. going to close issue
