### ISSUE TITLE
On import, keep swagger data as attributes

### ISSUE THREAD

**Issue by mbryzek** [mbryzek/apidoc#584]
example format:
```
          "attributes": [
            {
              "name": "swagger",
              "value": {
                "external_docs": [...],
                "security": {...}
              }
            }
          ]
```

capture

  - security
  - security definitions
  - external docs
  - example object
  - other?

**Comment by rlmartin** [comment]
I just added support for this to the Swagger export - just need to see it come through in the swagger.json :)

**Comment by fabiocognigni** [comment]
Regarding **externalDocs**: currently apidoc is combining the Swagger `externalDocs.description` and `externalDocs.url` into apidoc's `description` (see details for [operations](https://github.com/mbryzek/apidoc/blob/master/swagger/src/main/scala/me/apidoc/swagger/translators/Operation.scala#L45) and for [models](https://github.com/mbryzek/apidoc/blob/master/swagger/src/main/scala/me/apidoc/swagger/translators/Model.scala#L34-L39)).

@rlmartin @mbryzek Do you think this behaviour should remain the same after we import Swagger's externalDocs into Apidoc's `attributes` ?

**Comment by mbryzek** [comment]
i think maybe we should keep both - combine into apidoc's description so we can render in ui but keep the attributes so when we regenerate swagger we can favor the original swagger one
