### ISSUE TITLE
Support swagger yaml

### ISSUE THREAD

**Issue by mbryzek** [mbryzek/apidoc#585]
https://gist.github.com/earth2marsh/264123aefc2e29551d9d

uber public example attached
[uber.yaml.txt](https://github.com/mbryzek/apidoc/files/832042/uber.yaml.txt)

**Comment by fabiocognigni** [comment]
The Java [SwaggerParser we are using](https://github.com/mbryzek/apidoc/blob/master/swagger/src/main/scala/me/apidoc/swagger/Parser.scala#L28) already [accepts transparently both JSON and YAML files](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java).

In fact uploading a YAML spec file at apidoc.me already just works!!

I guess the only work needed here consists in changing the UI "labels" for:

* the file name in the `original` link in the left nav: something like`swagger.yaml`? (in case the file uploaded was yaml)
* the description in the `Type` dropdown (in the upload file UI): something like "Swagger (2.0, both JSON and YAML)" ?

Thoughts?

**Comment by mbryzek** [comment]
oh - that's great news! likely just a little bit of config to accept a file ending in .yaml and to detect that the yaml file is swagger

**Comment by fabiocognigni** [comment]
Not sure why merging https://github.com/mbryzek/apidoc/pull/618 didn't automatically close this issue (given there is a comment referencing to it). This can now be closed.
