### ISSUE TITLE
Schema for api.json

### ISSUE THREAD

**Issue by utdemir** [mbryzek/apidoc#605]
We have an apidoc schema for `service.json` here: https://www.apidoc.me/bryzek/apidoc-spec/latest

However, I couldn't find any apidoc schema for `api.json`. In other words, I'm looking for this one, https://www.apidoc.me/doc/apiJson , but as a JSON schema.

Do you have any?

**Comment by mbryzek** [comment]
Hi there - Is https://github.com/mbryzek/apidoc/blob/master/spec/apidoc-api.json what you are looking for?

**Comment by utdemir** [comment]
Thank you @mbryzek , but it's not.

I'm looking for a specification of api.json schema. Pretty similar to https://www.apidoc.me/bryzek/apidoc-spec/0.11.68/original , only for `api.json` instead of `service.json`.

By the way, description field on the link I mentioned is a bit misleading, it says "specification of api.json", but it is actually a specification of service.json.

**Comment by mbryzek** [comment]
i see - sorry - we don't have one available. curious - what are you looking to do?

**Comment by utdemir** [comment]
Thank you @mbryzek , it shouldn't be too hard to write it myself then :).

I'm trying to write a parser for `api.json` files, and I thought instead of writing the whole parser myself, I could write a smaller parser which can only parse the absolute necessary fields(only models/enums/unions, not resources/metadata/descriptions etc.) from api.json specification, and using that specification, generate a proper parser which can parse all fields.

Thanks for quick answers, I'll send a PR when I finish writing the spec :).

**Comment by mbryzek** [comment]
Interesting - FYI all parsers i see folks using are based on the service spec as the service spec fills in all the inferred values and also handles other input formats (Avro, swagger).

**Comment by utdemir** [comment]
@mbryzek , thanks, it looks like using service spec is a better idea. I'll use the existing spec then :).

Thanks again.

**Comment by kalmanb** [comment]
@mbryzek I had a chat to @utdemir (he sit's two desks away) and sold him on the benefits of service spec ;)

**Comment by mbryzek** [comment]
cool - and btw if you are using the cli (https://github.com/mbryzek/apidoc-cli), you can download the service spec with `apidoc download` command, eg:

`apidoc download bryzek apidoc-api latest service`
