### ISSUE TITLE
Allow scala code generation for model types with > 22 fields

### ISSUE THREAD

**Issue by gheine** [mbryzek/apidoc#617]
Limitation due to case class arg limit of 22 in scala 2.10 and before. This limit has been lifted since scala 2.11, and since scala 2.12 is out for more than 6 months, we could consider dropping support for scala 2.10 and older, or at least generate case classes with more than 22 fields, which would not compile with 2.10.

Alternative could be to use normal classes instead of case classes for types with more than 22 fields.

**Comment by mbryzek** [comment]
do you know if this now work w/ play-json (IIRC they were trailing the scala change to support more than 22 fields)

**Comment by gheine** [comment]
Not for sure. Would be a matter of trying it out.

**Comment by mbryzek** [comment]
validated removed here: https://github.com/mbryzek/apidoc-generator/pull/199

**Comment by mbryzek** [comment]
deploying now

**Comment by gheine** [comment]
Awesome, thanks @mbryzek!
